name: 'dca crypto job'

on:
  schedule:
    - cron: '0 12 */1 * *' # At 12:00 UTC every day

jobs:
  buy-crypto:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run purchase
